
spring:
    application:
        name: kids_chat

azure:
  open:
    ai: #GPT5
      endpoint: ${OPEN_AI_ENDPOINT}
      key: ${OPEN_AI_KEY}
  content:
    safety:
      endpoint: ${AZURE_CONTENT_SAFETY_ENDPOINT}
      api:
          key: ${AZURE_CONTENT_SAFETY_APIKEY}
  bullying: # GPT4
    endpoint: {AZURE_BULLYING_ENDPOINT}
    api:
      key: ${AZURE_BULLYING_APIKEY}

ai:
  answer-mode: RAG_ONLY
  #RAG_ONLY
  #GPT_ONLY

